### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by PriceChild** [insipx/Ergo#31]
Hi @insipx would you be able to choose a licence on this repository to make the right to reuse clearer?

FWIW zola is under a basic MIT licence which I suspect may be appropriate here also, but it's entirely up to you?

Thanks!

**Comment by insipx** [comment]
Didn't even realize I didn't have one, thanks for the hint!

Added Ergo under MIT

**Comment by JoePricey** [comment]
@insipx Brilliant thank you!
